version = 0.1

[default.deploy.parameters]
stack_name = "sample-lambda-endpoint"
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
region = "us-east-1"
parameter_overrides = "AssumeRoleArn=arn:aws:iam::902747178791:role/STS_Trusted_Role GcpSaSecretName=sample/gcp/secret"